server:
  port: 8002         #当前服务的端口号
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  # mybatis配置文件所在路径
  type-aliases-package: com.project.bean              # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/*.xml    # mapper映射文件
    
spring:
   application:
    name: woniucloud-provider   #当前服务的名字，后面会用到
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource       # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver           # mysql驱动包
    url: jdbc:mysql://localhost:3306/test              # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                      # 数据库连接池的最小维持连接数
      initial-size: 5                                  # 初始化连接数
      max-total: 5                                     # 最大连接数
      max-wait-millis: 200                             # 等待连接获取的最大超时时间
      
eureka:
  client:
    service-url:
      defaultZone:  http://eurakeserver9000.com:9000/eureka,http://eurakeserver9001.com:9001/eureka,http://eurakeserver9002.com:9002/eureka
    
  instance:
    instance-id: woniu46cloud-provider-8002
    prefer-ip-address: true 
    
info: #监控信息 
  app.name: woniucloud
  company.name: www.woniuxy.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$